### ISSUE TITLE
Question: where is the code that talks with Hashicorp Vault?

### ISSUE THREAD

**Issue by canidam** [OT-CONTAINER-KIT/k8s-vault-webhook#18]
I was glancing over the code, but couldn't find the part when using Hashicorp Vault, where you replace the pod annotations with the actual secrets? Also the example in the docs show the annotations rather than the pass - https://ot-container-kit.github.io/k8s-vault-webhook/guide/hashicorp-vault-example.html

**Comment by DVGeoffrey** [comment]
👍  I would like to know this too

**Comment by iamabhishek-dubey** [comment]
https://github.com/OT-CONTAINER-KIT/k8s-vault-webhook/blob/master/vault.go
